// -------------------------------------------------------------
//
// Module: FIR_9600Hz
// Generated by MATLAB(R) 9.12 and Filter Design HDL Coder 3.1.11.
// Generated on: 2023-04-24 12:51:14
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: FIR_9600Hz
// Name: FIR_9600Hz
// TargetLanguage: Verilog
// TestBenchName: FIR_9600Hz_tb
// TestBenchStimulus: impulse step ramp chirp noise 

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------




// `timescale 1 ns / 1 ns

module FIR_9600Hz
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [31:0] filter_in; //sfix32_En31
  output  signed [66:0] filter_out; //sfix67_En65

////////////////////////////////////////////////////////////////
//Module Architecture: FIR_9600Hz
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [31:0] coeff1 = 32'h007FD39C; //sfix32_En34
  parameter signed [31:0] coeff2 = 32'h006763AB; //sfix32_En34
  parameter signed [31:0] coeff3 = 32'h0041611B; //sfix32_En34
  parameter signed [31:0] coeff4 = 32'hFFFEBD83; //sfix32_En34
  parameter signed [31:0] coeff5 = 32'hFF8E06E2; //sfix32_En34
  parameter signed [31:0] coeff6 = 32'hFEE061B9; //sfix32_En34
  parameter signed [31:0] coeff7 = 32'hFDEF8CCF; //sfix32_En34
  parameter signed [31:0] coeff8 = 32'hFCC3E4CC; //sfix32_En34
  parameter signed [31:0] coeff9 = 32'hFB793229; //sfix32_En34
  parameter signed [31:0] coeff10 = 32'hFA41142B; //sfix32_En34
  parameter signed [31:0] coeff11 = 32'hF9621B46; //sfix32_En34
  parameter signed [31:0] coeff12 = 32'hF93316C1; //sfix32_En34
  parameter signed [31:0] coeff13 = 32'hFA12ADAE; //sfix32_En34
  parameter signed [31:0] coeff14 = 32'hFC5BFC15; //sfix32_En34
  parameter signed [31:0] coeff15 = 32'h00598077; //sfix32_En34
  parameter signed [31:0] coeff16 = 32'h0638120E; //sfix32_En34
  parameter signed [31:0] coeff17 = 32'h0DFBC861; //sfix32_En34
  parameter signed [31:0] coeff18 = 32'h1778A4AE; //sfix32_En34
  parameter signed [31:0] coeff19 = 32'h22506C37; //sfix32_En34
  parameter signed [31:0] coeff20 = 32'h2DF681F4; //sfix32_En34
  parameter signed [31:0] coeff21 = 32'h39B9C411; //sfix32_En34
  parameter signed [31:0] coeff22 = 32'h44D39ABA; //sfix32_En34
  parameter signed [31:0] coeff23 = 32'h4E7AA1D9; //sfix32_En34
  parameter signed [31:0] coeff24 = 32'h55F6C538; //sfix32_En34
  parameter signed [31:0] coeff25 = 32'h5AB45D5D; //sfix32_En34
  parameter signed [31:0] coeff26 = 32'h5C53E864; //sfix32_En34
  parameter signed [31:0] coeff27 = 32'h5AB45D5D; //sfix32_En34
  parameter signed [31:0] coeff28 = 32'h55F6C538; //sfix32_En34
  parameter signed [31:0] coeff29 = 32'h4E7AA1D9; //sfix32_En34
  parameter signed [31:0] coeff30 = 32'h44D39ABA; //sfix32_En34
  parameter signed [31:0] coeff31 = 32'h39B9C411; //sfix32_En34
  parameter signed [31:0] coeff32 = 32'h2DF681F4; //sfix32_En34
  parameter signed [31:0] coeff33 = 32'h22506C37; //sfix32_En34
  parameter signed [31:0] coeff34 = 32'h1778A4AE; //sfix32_En34
  parameter signed [31:0] coeff35 = 32'h0DFBC861; //sfix32_En34
  parameter signed [31:0] coeff36 = 32'h0638120E; //sfix32_En34
  parameter signed [31:0] coeff37 = 32'h00598077; //sfix32_En34
  parameter signed [31:0] coeff38 = 32'hFC5BFC15; //sfix32_En34
  parameter signed [31:0] coeff39 = 32'hFA12ADAE; //sfix32_En34
  parameter signed [31:0] coeff40 = 32'hF93316C1; //sfix32_En34
  parameter signed [31:0] coeff41 = 32'hF9621B46; //sfix32_En34
  parameter signed [31:0] coeff42 = 32'hFA41142B; //sfix32_En34
  parameter signed [31:0] coeff43 = 32'hFB793229; //sfix32_En34
  parameter signed [31:0] coeff44 = 32'hFCC3E4CC; //sfix32_En34
  parameter signed [31:0] coeff45 = 32'hFDEF8CCF; //sfix32_En34
  parameter signed [31:0] coeff46 = 32'hFEE061B9; //sfix32_En34
  parameter signed [31:0] coeff47 = 32'hFF8E06E2; //sfix32_En34
  parameter signed [31:0] coeff48 = 32'hFFFEBD83; //sfix32_En34
  parameter signed [31:0] coeff49 = 32'h0041611B; //sfix32_En34
  parameter signed [31:0] coeff50 = 32'h006763AB; //sfix32_En34
  parameter signed [31:0] coeff51 = 32'h007FD39C; //sfix32_En34

  // Signals
  reg  signed [31:0] delay_pipeline [0:50] ; // sfix32_En31
  wire signed [62:0] product51; // sfix63_En65
  wire signed [63:0] mul_temp; // sfix64_En65
  wire signed [62:0] product50; // sfix63_En65
  wire signed [63:0] mul_temp_1; // sfix64_En65
  wire signed [62:0] product49; // sfix63_En65
  wire signed [63:0] mul_temp_2; // sfix64_En65
  wire signed [62:0] product48; // sfix63_En65
  wire signed [63:0] mul_temp_3; // sfix64_En65
  wire signed [62:0] product47; // sfix63_En65
  wire signed [63:0] mul_temp_4; // sfix64_En65
  wire signed [62:0] product46; // sfix63_En65
  wire signed [63:0] mul_temp_5; // sfix64_En65
  wire signed [62:0] product45; // sfix63_En65
  wire signed [63:0] mul_temp_6; // sfix64_En65
  wire signed [62:0] product44; // sfix63_En65
  wire signed [63:0] mul_temp_7; // sfix64_En65
  wire signed [62:0] product43; // sfix63_En65
  wire signed [63:0] mul_temp_8; // sfix64_En65
  wire signed [62:0] product42; // sfix63_En65
  wire signed [63:0] mul_temp_9; // sfix64_En65
  wire signed [62:0] product41; // sfix63_En65
  wire signed [63:0] mul_temp_10; // sfix64_En65
  wire signed [62:0] product40; // sfix63_En65
  wire signed [63:0] mul_temp_11; // sfix64_En65
  wire signed [62:0] product39; // sfix63_En65
  wire signed [63:0] mul_temp_12; // sfix64_En65
  wire signed [62:0] product38; // sfix63_En65
  wire signed [63:0] mul_temp_13; // sfix64_En65
  wire signed [62:0] product37; // sfix63_En65
  wire signed [63:0] mul_temp_14; // sfix64_En65
  wire signed [62:0] product36; // sfix63_En65
  wire signed [63:0] mul_temp_15; // sfix64_En65
  wire signed [62:0] product35; // sfix63_En65
  wire signed [63:0] mul_temp_16; // sfix64_En65
  wire signed [62:0] product34; // sfix63_En65
  wire signed [63:0] mul_temp_17; // sfix64_En65
  wire signed [62:0] product33; // sfix63_En65
  wire signed [63:0] mul_temp_18; // sfix64_En65
  wire signed [62:0] product32; // sfix63_En65
  wire signed [63:0] mul_temp_19; // sfix64_En65
  wire signed [62:0] product31; // sfix63_En65
  wire signed [63:0] mul_temp_20; // sfix64_En65
  wire signed [62:0] product30; // sfix63_En65
  wire signed [63:0] mul_temp_21; // sfix64_En65
  wire signed [62:0] product29; // sfix63_En65
  wire signed [63:0] mul_temp_22; // sfix64_En65
  wire signed [62:0] product28; // sfix63_En65
  wire signed [63:0] mul_temp_23; // sfix64_En65
  wire signed [62:0] product27; // sfix63_En65
  wire signed [63:0] mul_temp_24; // sfix64_En65
  wire signed [62:0] product26; // sfix63_En65
  wire signed [63:0] mul_temp_25; // sfix64_En65
  wire signed [62:0] product25; // sfix63_En65
  wire signed [63:0] mul_temp_26; // sfix64_En65
  wire signed [62:0] product24; // sfix63_En65
  wire signed [63:0] mul_temp_27; // sfix64_En65
  wire signed [62:0] product23; // sfix63_En65
  wire signed [63:0] mul_temp_28; // sfix64_En65
  wire signed [62:0] product22; // sfix63_En65
  wire signed [63:0] mul_temp_29; // sfix64_En65
  wire signed [62:0] product21; // sfix63_En65
  wire signed [63:0] mul_temp_30; // sfix64_En65
  wire signed [62:0] product20; // sfix63_En65
  wire signed [63:0] mul_temp_31; // sfix64_En65
  wire signed [62:0] product19; // sfix63_En65
  wire signed [63:0] mul_temp_32; // sfix64_En65
  wire signed [62:0] product18; // sfix63_En65
  wire signed [63:0] mul_temp_33; // sfix64_En65
  wire signed [62:0] product17; // sfix63_En65
  wire signed [63:0] mul_temp_34; // sfix64_En65
  wire signed [62:0] product16; // sfix63_En65
  wire signed [63:0] mul_temp_35; // sfix64_En65
  wire signed [62:0] product15; // sfix63_En65
  wire signed [63:0] mul_temp_36; // sfix64_En65
  wire signed [62:0] product14; // sfix63_En65
  wire signed [63:0] mul_temp_37; // sfix64_En65
  wire signed [62:0] product13; // sfix63_En65
  wire signed [63:0] mul_temp_38; // sfix64_En65
  wire signed [62:0] product12; // sfix63_En65
  wire signed [63:0] mul_temp_39; // sfix64_En65
  wire signed [62:0] product11; // sfix63_En65
  wire signed [63:0] mul_temp_40; // sfix64_En65
  wire signed [62:0] product10; // sfix63_En65
  wire signed [63:0] mul_temp_41; // sfix64_En65
  wire signed [62:0] product9; // sfix63_En65
  wire signed [63:0] mul_temp_42; // sfix64_En65
  wire signed [62:0] product8; // sfix63_En65
  wire signed [63:0] mul_temp_43; // sfix64_En65
  wire signed [62:0] product7; // sfix63_En65
  wire signed [63:0] mul_temp_44; // sfix64_En65
  wire signed [62:0] product6; // sfix63_En65
  wire signed [63:0] mul_temp_45; // sfix64_En65
  wire signed [62:0] product5; // sfix63_En65
  wire signed [63:0] mul_temp_46; // sfix64_En65
  wire signed [62:0] product4; // sfix63_En65
  wire signed [63:0] mul_temp_47; // sfix64_En65
  wire signed [62:0] product3; // sfix63_En65
  wire signed [63:0] mul_temp_48; // sfix64_En65
  wire signed [62:0] product2; // sfix63_En65
  wire signed [63:0] mul_temp_49; // sfix64_En65
  wire signed [66:0] product1_cast; // sfix67_En65
  wire signed [62:0] product1; // sfix63_En65
  wire signed [63:0] mul_temp_50; // sfix64_En65
  wire signed [66:0] sum1; // sfix67_En65
  wire signed [66:0] add_signext; // sfix67_En65
  wire signed [66:0] add_signext_1; // sfix67_En65
  wire signed [67:0] add_temp; // sfix68_En65
  wire signed [66:0] sum2; // sfix67_En65
  wire signed [66:0] add_signext_2; // sfix67_En65
  wire signed [66:0] add_signext_3; // sfix67_En65
  wire signed [67:0] add_temp_1; // sfix68_En65
  wire signed [66:0] sum3; // sfix67_En65
  wire signed [66:0] add_signext_4; // sfix67_En65
  wire signed [66:0] add_signext_5; // sfix67_En65
  wire signed [67:0] add_temp_2; // sfix68_En65
  wire signed [66:0] sum4; // sfix67_En65
  wire signed [66:0] add_signext_6; // sfix67_En65
  wire signed [66:0] add_signext_7; // sfix67_En65
  wire signed [67:0] add_temp_3; // sfix68_En65
  wire signed [66:0] sum5; // sfix67_En65
  wire signed [66:0] add_signext_8; // sfix67_En65
  wire signed [66:0] add_signext_9; // sfix67_En65
  wire signed [67:0] add_temp_4; // sfix68_En65
  wire signed [66:0] sum6; // sfix67_En65
  wire signed [66:0] add_signext_10; // sfix67_En65
  wire signed [66:0] add_signext_11; // sfix67_En65
  wire signed [67:0] add_temp_5; // sfix68_En65
  wire signed [66:0] sum7; // sfix67_En65
  wire signed [66:0] add_signext_12; // sfix67_En65
  wire signed [66:0] add_signext_13; // sfix67_En65
  wire signed [67:0] add_temp_6; // sfix68_En65
  wire signed [66:0] sum8; // sfix67_En65
  wire signed [66:0] add_signext_14; // sfix67_En65
  wire signed [66:0] add_signext_15; // sfix67_En65
  wire signed [67:0] add_temp_7; // sfix68_En65
  wire signed [66:0] sum9; // sfix67_En65
  wire signed [66:0] add_signext_16; // sfix67_En65
  wire signed [66:0] add_signext_17; // sfix67_En65
  wire signed [67:0] add_temp_8; // sfix68_En65
  wire signed [66:0] sum10; // sfix67_En65
  wire signed [66:0] add_signext_18; // sfix67_En65
  wire signed [66:0] add_signext_19; // sfix67_En65
  wire signed [67:0] add_temp_9; // sfix68_En65
  wire signed [66:0] sum11; // sfix67_En65
  wire signed [66:0] add_signext_20; // sfix67_En65
  wire signed [66:0] add_signext_21; // sfix67_En65
  wire signed [67:0] add_temp_10; // sfix68_En65
  wire signed [66:0] sum12; // sfix67_En65
  wire signed [66:0] add_signext_22; // sfix67_En65
  wire signed [66:0] add_signext_23; // sfix67_En65
  wire signed [67:0] add_temp_11; // sfix68_En65
  wire signed [66:0] sum13; // sfix67_En65
  wire signed [66:0] add_signext_24; // sfix67_En65
  wire signed [66:0] add_signext_25; // sfix67_En65
  wire signed [67:0] add_temp_12; // sfix68_En65
  wire signed [66:0] sum14; // sfix67_En65
  wire signed [66:0] add_signext_26; // sfix67_En65
  wire signed [66:0] add_signext_27; // sfix67_En65
  wire signed [67:0] add_temp_13; // sfix68_En65
  wire signed [66:0] sum15; // sfix67_En65
  wire signed [66:0] add_signext_28; // sfix67_En65
  wire signed [66:0] add_signext_29; // sfix67_En65
  wire signed [67:0] add_temp_14; // sfix68_En65
  wire signed [66:0] sum16; // sfix67_En65
  wire signed [66:0] add_signext_30; // sfix67_En65
  wire signed [66:0] add_signext_31; // sfix67_En65
  wire signed [67:0] add_temp_15; // sfix68_En65
  wire signed [66:0] sum17; // sfix67_En65
  wire signed [66:0] add_signext_32; // sfix67_En65
  wire signed [66:0] add_signext_33; // sfix67_En65
  wire signed [67:0] add_temp_16; // sfix68_En65
  wire signed [66:0] sum18; // sfix67_En65
  wire signed [66:0] add_signext_34; // sfix67_En65
  wire signed [66:0] add_signext_35; // sfix67_En65
  wire signed [67:0] add_temp_17; // sfix68_En65
  wire signed [66:0] sum19; // sfix67_En65
  wire signed [66:0] add_signext_36; // sfix67_En65
  wire signed [66:0] add_signext_37; // sfix67_En65
  wire signed [67:0] add_temp_18; // sfix68_En65
  wire signed [66:0] sum20; // sfix67_En65
  wire signed [66:0] add_signext_38; // sfix67_En65
  wire signed [66:0] add_signext_39; // sfix67_En65
  wire signed [67:0] add_temp_19; // sfix68_En65
  wire signed [66:0] sum21; // sfix67_En65
  wire signed [66:0] add_signext_40; // sfix67_En65
  wire signed [66:0] add_signext_41; // sfix67_En65
  wire signed [67:0] add_temp_20; // sfix68_En65
  wire signed [66:0] sum22; // sfix67_En65
  wire signed [66:0] add_signext_42; // sfix67_En65
  wire signed [66:0] add_signext_43; // sfix67_En65
  wire signed [67:0] add_temp_21; // sfix68_En65
  wire signed [66:0] sum23; // sfix67_En65
  wire signed [66:0] add_signext_44; // sfix67_En65
  wire signed [66:0] add_signext_45; // sfix67_En65
  wire signed [67:0] add_temp_22; // sfix68_En65
  wire signed [66:0] sum24; // sfix67_En65
  wire signed [66:0] add_signext_46; // sfix67_En65
  wire signed [66:0] add_signext_47; // sfix67_En65
  wire signed [67:0] add_temp_23; // sfix68_En65
  wire signed [66:0] sum25; // sfix67_En65
  wire signed [66:0] add_signext_48; // sfix67_En65
  wire signed [66:0] add_signext_49; // sfix67_En65
  wire signed [67:0] add_temp_24; // sfix68_En65
  wire signed [66:0] sum26; // sfix67_En65
  wire signed [66:0] add_signext_50; // sfix67_En65
  wire signed [66:0] add_signext_51; // sfix67_En65
  wire signed [67:0] add_temp_25; // sfix68_En65
  wire signed [66:0] sum27; // sfix67_En65
  wire signed [66:0] add_signext_52; // sfix67_En65
  wire signed [66:0] add_signext_53; // sfix67_En65
  wire signed [67:0] add_temp_26; // sfix68_En65
  wire signed [66:0] sum28; // sfix67_En65
  wire signed [66:0] add_signext_54; // sfix67_En65
  wire signed [66:0] add_signext_55; // sfix67_En65
  wire signed [67:0] add_temp_27; // sfix68_En65
  wire signed [66:0] sum29; // sfix67_En65
  wire signed [66:0] add_signext_56; // sfix67_En65
  wire signed [66:0] add_signext_57; // sfix67_En65
  wire signed [67:0] add_temp_28; // sfix68_En65
  wire signed [66:0] sum30; // sfix67_En65
  wire signed [66:0] add_signext_58; // sfix67_En65
  wire signed [66:0] add_signext_59; // sfix67_En65
  wire signed [67:0] add_temp_29; // sfix68_En65
  wire signed [66:0] sum31; // sfix67_En65
  wire signed [66:0] add_signext_60; // sfix67_En65
  wire signed [66:0] add_signext_61; // sfix67_En65
  wire signed [67:0] add_temp_30; // sfix68_En65
  wire signed [66:0] sum32; // sfix67_En65
  wire signed [66:0] add_signext_62; // sfix67_En65
  wire signed [66:0] add_signext_63; // sfix67_En65
  wire signed [67:0] add_temp_31; // sfix68_En65
  wire signed [66:0] sum33; // sfix67_En65
  wire signed [66:0] add_signext_64; // sfix67_En65
  wire signed [66:0] add_signext_65; // sfix67_En65
  wire signed [67:0] add_temp_32; // sfix68_En65
  wire signed [66:0] sum34; // sfix67_En65
  wire signed [66:0] add_signext_66; // sfix67_En65
  wire signed [66:0] add_signext_67; // sfix67_En65
  wire signed [67:0] add_temp_33; // sfix68_En65
  wire signed [66:0] sum35; // sfix67_En65
  wire signed [66:0] add_signext_68; // sfix67_En65
  wire signed [66:0] add_signext_69; // sfix67_En65
  wire signed [67:0] add_temp_34; // sfix68_En65
  wire signed [66:0] sum36; // sfix67_En65
  wire signed [66:0] add_signext_70; // sfix67_En65
  wire signed [66:0] add_signext_71; // sfix67_En65
  wire signed [67:0] add_temp_35; // sfix68_En65
  wire signed [66:0] sum37; // sfix67_En65
  wire signed [66:0] add_signext_72; // sfix67_En65
  wire signed [66:0] add_signext_73; // sfix67_En65
  wire signed [67:0] add_temp_36; // sfix68_En65
  wire signed [66:0] sum38; // sfix67_En65
  wire signed [66:0] add_signext_74; // sfix67_En65
  wire signed [66:0] add_signext_75; // sfix67_En65
  wire signed [67:0] add_temp_37; // sfix68_En65
  wire signed [66:0] sum39; // sfix67_En65
  wire signed [66:0] add_signext_76; // sfix67_En65
  wire signed [66:0] add_signext_77; // sfix67_En65
  wire signed [67:0] add_temp_38; // sfix68_En65
  wire signed [66:0] sum40; // sfix67_En65
  wire signed [66:0] add_signext_78; // sfix67_En65
  wire signed [66:0] add_signext_79; // sfix67_En65
  wire signed [67:0] add_temp_39; // sfix68_En65
  wire signed [66:0] sum41; // sfix67_En65
  wire signed [66:0] add_signext_80; // sfix67_En65
  wire signed [66:0] add_signext_81; // sfix67_En65
  wire signed [67:0] add_temp_40; // sfix68_En65
  wire signed [66:0] sum42; // sfix67_En65
  wire signed [66:0] add_signext_82; // sfix67_En65
  wire signed [66:0] add_signext_83; // sfix67_En65
  wire signed [67:0] add_temp_41; // sfix68_En65
  wire signed [66:0] sum43; // sfix67_En65
  wire signed [66:0] add_signext_84; // sfix67_En65
  wire signed [66:0] add_signext_85; // sfix67_En65
  wire signed [67:0] add_temp_42; // sfix68_En65
  wire signed [66:0] sum44; // sfix67_En65
  wire signed [66:0] add_signext_86; // sfix67_En65
  wire signed [66:0] add_signext_87; // sfix67_En65
  wire signed [67:0] add_temp_43; // sfix68_En65
  wire signed [66:0] sum45; // sfix67_En65
  wire signed [66:0] add_signext_88; // sfix67_En65
  wire signed [66:0] add_signext_89; // sfix67_En65
  wire signed [67:0] add_temp_44; // sfix68_En65
  wire signed [66:0] sum46; // sfix67_En65
  wire signed [66:0] add_signext_90; // sfix67_En65
  wire signed [66:0] add_signext_91; // sfix67_En65
  wire signed [67:0] add_temp_45; // sfix68_En65
  wire signed [66:0] sum47; // sfix67_En65
  wire signed [66:0] add_signext_92; // sfix67_En65
  wire signed [66:0] add_signext_93; // sfix67_En65
  wire signed [67:0] add_temp_46; // sfix68_En65
  wire signed [66:0] sum48; // sfix67_En65
  wire signed [66:0] add_signext_94; // sfix67_En65
  wire signed [66:0] add_signext_95; // sfix67_En65
  wire signed [67:0] add_temp_47; // sfix68_En65
  wire signed [66:0] sum49; // sfix67_En65
  wire signed [66:0] add_signext_96; // sfix67_En65
  wire signed [66:0] add_signext_97; // sfix67_En65
  wire signed [67:0] add_temp_48; // sfix68_En65
  wire signed [66:0] sum50; // sfix67_En65
  wire signed [66:0] add_signext_98; // sfix67_En65
  wire signed [66:0] add_signext_99; // sfix67_En65
  wire signed [67:0] add_temp_49; // sfix68_En65
  reg  signed [66:0] output_register; // sfix67_En65

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
        delay_pipeline[32] <= 0;
        delay_pipeline[33] <= 0;
        delay_pipeline[34] <= 0;
        delay_pipeline[35] <= 0;
        delay_pipeline[36] <= 0;
        delay_pipeline[37] <= 0;
        delay_pipeline[38] <= 0;
        delay_pipeline[39] <= 0;
        delay_pipeline[40] <= 0;
        delay_pipeline[41] <= 0;
        delay_pipeline[42] <= 0;
        delay_pipeline[43] <= 0;
        delay_pipeline[44] <= 0;
        delay_pipeline[45] <= 0;
        delay_pipeline[46] <= 0;
        delay_pipeline[47] <= 0;
        delay_pipeline[48] <= 0;
        delay_pipeline[49] <= 0;
        delay_pipeline[50] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
          delay_pipeline[32] <= delay_pipeline[31];
          delay_pipeline[33] <= delay_pipeline[32];
          delay_pipeline[34] <= delay_pipeline[33];
          delay_pipeline[35] <= delay_pipeline[34];
          delay_pipeline[36] <= delay_pipeline[35];
          delay_pipeline[37] <= delay_pipeline[36];
          delay_pipeline[38] <= delay_pipeline[37];
          delay_pipeline[39] <= delay_pipeline[38];
          delay_pipeline[40] <= delay_pipeline[39];
          delay_pipeline[41] <= delay_pipeline[40];
          delay_pipeline[42] <= delay_pipeline[41];
          delay_pipeline[43] <= delay_pipeline[42];
          delay_pipeline[44] <= delay_pipeline[43];
          delay_pipeline[45] <= delay_pipeline[44];
          delay_pipeline[46] <= delay_pipeline[45];
          delay_pipeline[47] <= delay_pipeline[46];
          delay_pipeline[48] <= delay_pipeline[47];
          delay_pipeline[49] <= delay_pipeline[48];
          delay_pipeline[50] <= delay_pipeline[49];
        end
      end
    end // Delay_Pipeline_process


  assign mul_temp = delay_pipeline[50] * coeff51;
  assign product51 = mul_temp[62:0];

  assign mul_temp_1 = delay_pipeline[49] * coeff50;
  assign product50 = mul_temp_1[62:0];

  assign mul_temp_2 = delay_pipeline[48] * coeff49;
  assign product49 = mul_temp_2[62:0];

  assign mul_temp_3 = delay_pipeline[47] * coeff48;
  assign product48 = mul_temp_3[62:0];

  assign mul_temp_4 = delay_pipeline[46] * coeff47;
  assign product47 = mul_temp_4[62:0];

  assign mul_temp_5 = delay_pipeline[45] * coeff46;
  assign product46 = mul_temp_5[62:0];

  assign mul_temp_6 = delay_pipeline[44] * coeff45;
  assign product45 = mul_temp_6[62:0];

  assign mul_temp_7 = delay_pipeline[43] * coeff44;
  assign product44 = mul_temp_7[62:0];

  assign mul_temp_8 = delay_pipeline[42] * coeff43;
  assign product43 = mul_temp_8[62:0];

  assign mul_temp_9 = delay_pipeline[41] * coeff42;
  assign product42 = mul_temp_9[62:0];

  assign mul_temp_10 = delay_pipeline[40] * coeff41;
  assign product41 = mul_temp_10[62:0];

  assign mul_temp_11 = delay_pipeline[39] * coeff40;
  assign product40 = mul_temp_11[62:0];

  assign mul_temp_12 = delay_pipeline[38] * coeff39;
  assign product39 = mul_temp_12[62:0];

  assign mul_temp_13 = delay_pipeline[37] * coeff38;
  assign product38 = mul_temp_13[62:0];

  assign mul_temp_14 = delay_pipeline[36] * coeff37;
  assign product37 = mul_temp_14[62:0];

  assign mul_temp_15 = delay_pipeline[35] * coeff36;
  assign product36 = mul_temp_15[62:0];

  assign mul_temp_16 = delay_pipeline[34] * coeff35;
  assign product35 = mul_temp_16[62:0];

  assign mul_temp_17 = delay_pipeline[33] * coeff34;
  assign product34 = mul_temp_17[62:0];

  assign mul_temp_18 = delay_pipeline[32] * coeff33;
  assign product33 = mul_temp_18[62:0];

  assign mul_temp_19 = delay_pipeline[31] * coeff32;
  assign product32 = mul_temp_19[62:0];

  assign mul_temp_20 = delay_pipeline[30] * coeff31;
  assign product31 = mul_temp_20[62:0];

  assign mul_temp_21 = delay_pipeline[29] * coeff30;
  assign product30 = mul_temp_21[62:0];

  assign mul_temp_22 = delay_pipeline[28] * coeff29;
  assign product29 = mul_temp_22[62:0];

  assign mul_temp_23 = delay_pipeline[27] * coeff28;
  assign product28 = mul_temp_23[62:0];

  assign mul_temp_24 = delay_pipeline[26] * coeff27;
  assign product27 = mul_temp_24[62:0];

  assign mul_temp_25 = delay_pipeline[25] * coeff26;
  assign product26 = mul_temp_25[62:0];

  assign mul_temp_26 = delay_pipeline[24] * coeff25;
  assign product25 = mul_temp_26[62:0];

  assign mul_temp_27 = delay_pipeline[23] * coeff24;
  assign product24 = mul_temp_27[62:0];

  assign mul_temp_28 = delay_pipeline[22] * coeff23;
  assign product23 = mul_temp_28[62:0];

  assign mul_temp_29 = delay_pipeline[21] * coeff22;
  assign product22 = mul_temp_29[62:0];

  assign mul_temp_30 = delay_pipeline[20] * coeff21;
  assign product21 = mul_temp_30[62:0];

  assign mul_temp_31 = delay_pipeline[19] * coeff20;
  assign product20 = mul_temp_31[62:0];

  assign mul_temp_32 = delay_pipeline[18] * coeff19;
  assign product19 = mul_temp_32[62:0];

  assign mul_temp_33 = delay_pipeline[17] * coeff18;
  assign product18 = mul_temp_33[62:0];

  assign mul_temp_34 = delay_pipeline[16] * coeff17;
  assign product17 = mul_temp_34[62:0];

  assign mul_temp_35 = delay_pipeline[15] * coeff16;
  assign product16 = mul_temp_35[62:0];

  assign mul_temp_36 = delay_pipeline[14] * coeff15;
  assign product15 = mul_temp_36[62:0];

  assign mul_temp_37 = delay_pipeline[13] * coeff14;
  assign product14 = mul_temp_37[62:0];

  assign mul_temp_38 = delay_pipeline[12] * coeff13;
  assign product13 = mul_temp_38[62:0];

  assign mul_temp_39 = delay_pipeline[11] * coeff12;
  assign product12 = mul_temp_39[62:0];

  assign mul_temp_40 = delay_pipeline[10] * coeff11;
  assign product11 = mul_temp_40[62:0];

  assign mul_temp_41 = delay_pipeline[9] * coeff10;
  assign product10 = mul_temp_41[62:0];

  assign mul_temp_42 = delay_pipeline[8] * coeff9;
  assign product9 = mul_temp_42[62:0];

  assign mul_temp_43 = delay_pipeline[7] * coeff8;
  assign product8 = mul_temp_43[62:0];

  assign mul_temp_44 = delay_pipeline[6] * coeff7;
  assign product7 = mul_temp_44[62:0];

  assign mul_temp_45 = delay_pipeline[5] * coeff6;
  assign product6 = mul_temp_45[62:0];

  assign mul_temp_46 = delay_pipeline[4] * coeff5;
  assign product5 = mul_temp_46[62:0];

  assign mul_temp_47 = delay_pipeline[3] * coeff4;
  assign product4 = mul_temp_47[62:0];

  assign mul_temp_48 = delay_pipeline[2] * coeff3;
  assign product3 = mul_temp_48[62:0];

  assign mul_temp_49 = delay_pipeline[1] * coeff2;
  assign product2 = mul_temp_49[62:0];

  assign product1_cast = $signed({{4{product1[62]}}, product1});

  assign mul_temp_50 = delay_pipeline[0] * coeff1;
  assign product1 = mul_temp_50[62:0];

  assign add_signext = product1_cast;
  assign add_signext_1 = $signed({{4{product2[62]}}, product2});
  assign add_temp = add_signext + add_signext_1;
  assign sum1 = add_temp[66:0];

  assign add_signext_2 = sum1;
  assign add_signext_3 = $signed({{4{product3[62]}}, product3});
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum2 = add_temp_1[66:0];

  assign add_signext_4 = sum2;
  assign add_signext_5 = $signed({{4{product4[62]}}, product4});
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum3 = add_temp_2[66:0];

  assign add_signext_6 = sum3;
  assign add_signext_7 = $signed({{4{product5[62]}}, product5});
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum4 = add_temp_3[66:0];

  assign add_signext_8 = sum4;
  assign add_signext_9 = $signed({{4{product6[62]}}, product6});
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum5 = add_temp_4[66:0];

  assign add_signext_10 = sum5;
  assign add_signext_11 = $signed({{4{product7[62]}}, product7});
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum6 = add_temp_5[66:0];

  assign add_signext_12 = sum6;
  assign add_signext_13 = $signed({{4{product8[62]}}, product8});
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum7 = add_temp_6[66:0];

  assign add_signext_14 = sum7;
  assign add_signext_15 = $signed({{4{product9[62]}}, product9});
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum8 = add_temp_7[66:0];

  assign add_signext_16 = sum8;
  assign add_signext_17 = $signed({{4{product10[62]}}, product10});
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum9 = add_temp_8[66:0];

  assign add_signext_18 = sum9;
  assign add_signext_19 = $signed({{4{product11[62]}}, product11});
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum10 = add_temp_9[66:0];

  assign add_signext_20 = sum10;
  assign add_signext_21 = $signed({{4{product12[62]}}, product12});
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum11 = add_temp_10[66:0];

  assign add_signext_22 = sum11;
  assign add_signext_23 = $signed({{4{product13[62]}}, product13});
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum12 = add_temp_11[66:0];

  assign add_signext_24 = sum12;
  assign add_signext_25 = $signed({{4{product14[62]}}, product14});
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum13 = add_temp_12[66:0];

  assign add_signext_26 = sum13;
  assign add_signext_27 = $signed({{4{product15[62]}}, product15});
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum14 = add_temp_13[66:0];

  assign add_signext_28 = sum14;
  assign add_signext_29 = $signed({{4{product16[62]}}, product16});
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum15 = add_temp_14[66:0];

  assign add_signext_30 = sum15;
  assign add_signext_31 = $signed({{4{product17[62]}}, product17});
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum16 = add_temp_15[66:0];

  assign add_signext_32 = sum16;
  assign add_signext_33 = $signed({{4{product18[62]}}, product18});
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum17 = add_temp_16[66:0];

  assign add_signext_34 = sum17;
  assign add_signext_35 = $signed({{4{product19[62]}}, product19});
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum18 = add_temp_17[66:0];

  assign add_signext_36 = sum18;
  assign add_signext_37 = $signed({{4{product20[62]}}, product20});
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum19 = add_temp_18[66:0];

  assign add_signext_38 = sum19;
  assign add_signext_39 = $signed({{4{product21[62]}}, product21});
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum20 = add_temp_19[66:0];

  assign add_signext_40 = sum20;
  assign add_signext_41 = $signed({{4{product22[62]}}, product22});
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum21 = add_temp_20[66:0];

  assign add_signext_42 = sum21;
  assign add_signext_43 = $signed({{4{product23[62]}}, product23});
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum22 = add_temp_21[66:0];

  assign add_signext_44 = sum22;
  assign add_signext_45 = $signed({{4{product24[62]}}, product24});
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum23 = add_temp_22[66:0];

  assign add_signext_46 = sum23;
  assign add_signext_47 = $signed({{4{product25[62]}}, product25});
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum24 = add_temp_23[66:0];

  assign add_signext_48 = sum24;
  assign add_signext_49 = $signed({{4{product26[62]}}, product26});
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum25 = add_temp_24[66:0];

  assign add_signext_50 = sum25;
  assign add_signext_51 = $signed({{4{product27[62]}}, product27});
  assign add_temp_25 = add_signext_50 + add_signext_51;
  assign sum26 = add_temp_25[66:0];

  assign add_signext_52 = sum26;
  assign add_signext_53 = $signed({{4{product28[62]}}, product28});
  assign add_temp_26 = add_signext_52 + add_signext_53;
  assign sum27 = add_temp_26[66:0];

  assign add_signext_54 = sum27;
  assign add_signext_55 = $signed({{4{product29[62]}}, product29});
  assign add_temp_27 = add_signext_54 + add_signext_55;
  assign sum28 = add_temp_27[66:0];

  assign add_signext_56 = sum28;
  assign add_signext_57 = $signed({{4{product30[62]}}, product30});
  assign add_temp_28 = add_signext_56 + add_signext_57;
  assign sum29 = add_temp_28[66:0];

  assign add_signext_58 = sum29;
  assign add_signext_59 = $signed({{4{product31[62]}}, product31});
  assign add_temp_29 = add_signext_58 + add_signext_59;
  assign sum30 = add_temp_29[66:0];

  assign add_signext_60 = sum30;
  assign add_signext_61 = $signed({{4{product32[62]}}, product32});
  assign add_temp_30 = add_signext_60 + add_signext_61;
  assign sum31 = add_temp_30[66:0];

  assign add_signext_62 = sum31;
  assign add_signext_63 = $signed({{4{product33[62]}}, product33});
  assign add_temp_31 = add_signext_62 + add_signext_63;
  assign sum32 = add_temp_31[66:0];

  assign add_signext_64 = sum32;
  assign add_signext_65 = $signed({{4{product34[62]}}, product34});
  assign add_temp_32 = add_signext_64 + add_signext_65;
  assign sum33 = add_temp_32[66:0];

  assign add_signext_66 = sum33;
  assign add_signext_67 = $signed({{4{product35[62]}}, product35});
  assign add_temp_33 = add_signext_66 + add_signext_67;
  assign sum34 = add_temp_33[66:0];

  assign add_signext_68 = sum34;
  assign add_signext_69 = $signed({{4{product36[62]}}, product36});
  assign add_temp_34 = add_signext_68 + add_signext_69;
  assign sum35 = add_temp_34[66:0];

  assign add_signext_70 = sum35;
  assign add_signext_71 = $signed({{4{product37[62]}}, product37});
  assign add_temp_35 = add_signext_70 + add_signext_71;
  assign sum36 = add_temp_35[66:0];

  assign add_signext_72 = sum36;
  assign add_signext_73 = $signed({{4{product38[62]}}, product38});
  assign add_temp_36 = add_signext_72 + add_signext_73;
  assign sum37 = add_temp_36[66:0];

  assign add_signext_74 = sum37;
  assign add_signext_75 = $signed({{4{product39[62]}}, product39});
  assign add_temp_37 = add_signext_74 + add_signext_75;
  assign sum38 = add_temp_37[66:0];

  assign add_signext_76 = sum38;
  assign add_signext_77 = $signed({{4{product40[62]}}, product40});
  assign add_temp_38 = add_signext_76 + add_signext_77;
  assign sum39 = add_temp_38[66:0];

  assign add_signext_78 = sum39;
  assign add_signext_79 = $signed({{4{product41[62]}}, product41});
  assign add_temp_39 = add_signext_78 + add_signext_79;
  assign sum40 = add_temp_39[66:0];

  assign add_signext_80 = sum40;
  assign add_signext_81 = $signed({{4{product42[62]}}, product42});
  assign add_temp_40 = add_signext_80 + add_signext_81;
  assign sum41 = add_temp_40[66:0];

  assign add_signext_82 = sum41;
  assign add_signext_83 = $signed({{4{product43[62]}}, product43});
  assign add_temp_41 = add_signext_82 + add_signext_83;
  assign sum42 = add_temp_41[66:0];

  assign add_signext_84 = sum42;
  assign add_signext_85 = $signed({{4{product44[62]}}, product44});
  assign add_temp_42 = add_signext_84 + add_signext_85;
  assign sum43 = add_temp_42[66:0];

  assign add_signext_86 = sum43;
  assign add_signext_87 = $signed({{4{product45[62]}}, product45});
  assign add_temp_43 = add_signext_86 + add_signext_87;
  assign sum44 = add_temp_43[66:0];

  assign add_signext_88 = sum44;
  assign add_signext_89 = $signed({{4{product46[62]}}, product46});
  assign add_temp_44 = add_signext_88 + add_signext_89;
  assign sum45 = add_temp_44[66:0];

  assign add_signext_90 = sum45;
  assign add_signext_91 = $signed({{4{product47[62]}}, product47});
  assign add_temp_45 = add_signext_90 + add_signext_91;
  assign sum46 = add_temp_45[66:0];

  assign add_signext_92 = sum46;
  assign add_signext_93 = $signed({{4{product48[62]}}, product48});
  assign add_temp_46 = add_signext_92 + add_signext_93;
  assign sum47 = add_temp_46[66:0];

  assign add_signext_94 = sum47;
  assign add_signext_95 = $signed({{4{product49[62]}}, product49});
  assign add_temp_47 = add_signext_94 + add_signext_95;
  assign sum48 = add_temp_47[66:0];

  assign add_signext_96 = sum48;
  assign add_signext_97 = $signed({{4{product50[62]}}, product50});
  assign add_temp_48 = add_signext_96 + add_signext_97;
  assign sum49 = add_temp_48[66:0];

  assign add_signext_98 = sum49;
  assign add_signext_99 = $signed({{4{product51[62]}}, product51});
  assign add_temp_49 = add_signext_98 + add_signext_99;
  assign sum50 = add_temp_49[66:0];

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= sum50;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // FIR_9600Hz
